INSERT INTO exp_category(catName) VALUES
("Bills/Utilities"),
("Education"),
("EMI"),
("Entertainment"),
("Food & Drinks"),
("Grocery"),
("Health"),
("Insurance"),
("Investments"),
("Loan"),
("Air Tickets"),
("Beauty/Fitness"),
("Bike"),
("Books"),
("Breakfast"),
("Bus Fare"),
("Business"),
("Cable"),
("Car"),
("Cash Spend"),
("Cigarettes"),
("Clothes"),
("Coffee"),
("Cookies"),
("Courier"),
("Cycle"),
("Daily Care"),
("Dining"),
("Disco"),
("Donation"),
("Drinks"),
("Electricity"),
("Electronics"),
("Fast Food"),
("Flowers"),
("Games"),
("Petrol/Disel"),
("Gifts"),
("Jewellery"),
("Gym"),
("Health"),
("OYO"),
("Household"),
("Ice-cream"),
("Maid/Driver"),
("Maintenance"),
("Medical"),
("Miscellaneous"),
("Mutual Funds"),
("Office"),
("Pets"),
("Post Office"),
("Printing/Scanning"),
("Rent/Mortgage"),
("Salon"),
("Savings"),
("Shopping"),
("Stationery"),
("Stocks"),
("Tax"),
("Toys"),
("Transport"),
("Water")
